digit = '0'|'1'|...|'9';
lc_letter = 'a'|'b'|...|'z';
uc_letter = 'A'|'B'|...|'Z';

integer = <digit>, {<digit>};

programName = <uc_letter>, {<letter>};

output = 'DISPLAY', <integer>;

sequence = {<sequence>} <output>;

terminator = 'BEGIN'|'END', <programName>;

program = <terminator>, sequence, <terminator>;
